Сделал адаптивный декор для главной
htmlacademy-adaptive/235287-cat-energy-21 pull request #11
Opened 2020-12-16 21:54 UTC by RomanTkachev

Сверстал главную страницу. Несколько важных моментов:

1. С контентными изображениями пока что не заморачивался — они, по идее, должны быть в следующем задании
2. С пиксель-перфектом то же самое — сделал приблизительно похоже, но детально проработать планировал после добавления графики

2020-12-17 20:42 UTC, kosovych requested changes

2020-12-17 20:42 UTC, kosovych commented on source/sass/blocks/example-slider.scss
> +    margin-left: 22.5px;
ненужно писать дробные значения пикселей

2020-12-17 20:42 UTC, kosovych commented on source/catalog.html
>                <a class="main-nav__link" href="/index.html">Главная</a>
в тексте задания указано, что должен быть ПП, поэтому подтяни его плиз в рамках этой ДЗ, дальше будет проще

2020-12-17 20:42 UTC, kosovych commented on source/sass/blocks/programs.scss
>    &:active {
стрелочка по active тоже должна менять цвет

2020-12-17 20:42 UTC, kosovych commented on source/catalog.html
>              </li>
page-footer__copyright copyright сделай одной ссылкой

2020-12-17 20:42 UTC, kosovych commented on source/sass/blocks/example-slider.scss
> +.slider__bar {
добавь интерактивности

2020-12-23 07:40 UTC, kosovych requested changes

2020-12-23 07:40 UTC, kosovych commented on source/sass/blocks/example-slider.scss
> +  position: relative;
![image](https://user-images.githubusercontent.com/19348382/102971085-5c414f80-4501-11eb-8805-ec98c0899448.png)
растяни кота

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>          </nav>
![image](https://user-images.githubusercontent.com/19348382/102971266-be9a5000-4501-11eb-8559-9ed0e32367d3.png)

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>          </nav>
![image](https://user-images.githubusercontent.com/19348382/102971333-dd98e200-4501-11eb-998c-dfaf5160084c.png)

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>          </nav>
![image](https://user-images.githubusercontent.com/19348382/102971551-44b69680-4502-11eb-84c9-389b5eebb22d.png)
десктоп

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>          </nav>
![image](https://user-images.githubusercontent.com/19348382/102971635-6152ce80-4502-11eb-88d5-e556703e1a78.png)

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>          </nav>
![image](https://user-images.githubusercontent.com/19348382/102971736-919a6d00-4502-11eb-8529-6a976dc56314.png)

2020-12-23 07:40 UTC, kosovych commented on source/catalog.html
>              </li>
проверь интерактивность со стайлгайдом

2020-12-23 07:40 UTC, kosovych commented on source/sass/blocks/example-slider.scss
> +.slider__bar {
не исправлено

2020-12-23 16:19 UTC, RomanTkachev commented on source/catalog.html
>              </li>
> page-footer__copyright copyright сделай одной ссылкой

сделал

2020-12-23 16:42 UTC, RomanTkachev commented on source/sass/blocks/example-slider.scss
> +.slider__bar {
добавил интерактивность ползунку слайдера

2020-12-23 16:44 UTC, RomanTkachev commented on source/sass/blocks/example-slider.scss
> +  position: relative;
договорились исправить в следующем задании

2020-12-23 16:45 UTC, RomanTkachev commented on source/catalog.html
>          </nav>
договорились исправить в следующем задании

2020-12-23 16:45 UTC, RomanTkachev commented on source/catalog.html
>          </nav>
договорились исправить в следующем задании

2020-12-23 16:45 UTC, RomanTkachev commented on source/catalog.html
>          </nav>
договорились исправить в следующем задании

2020-12-23 17:03 UTC, RomanTkachev commented on source/catalog.html
>          </nav>
увеличил размеры и отцентровал

2020-12-23 17:10 UTC, RomanTkachev commented on source/catalog.html
>              </li>
исправил ошибку с цветом ссылок на разных страница на десктопном разрешении

2020-12-23 21:19 UTC, merged