стилизация страницы формы
htmlacademy-adaptive/235287-cat-energy-21 pull request #12
Opened 2020-12-29 17:58 UTC by RomanTkachev

2020-12-29 22:30 UTC, kosovych requested changes
- проверь здесь https://validator.w3.org/nu/#textarea

2020-12-29 22:30 UTC, kosovych commented on source/form.html
>      <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/103317633-6c42bd00-4a34-11eb-913f-7eec3df619f6.png)

2020-12-29 22:30 UTC, kosovych commented on source/form.html
>      <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/103317678-91cfc680-4a34-11eb-8d55-4f85d556b4e8.png)

2020-12-29 22:30 UTC, kosovych commented on source/form.html
>                  </label>
по фокусу элемент дергается (из-за рамки). нужно исправить

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +                  <input class="form__input form__input--radio" type="radio" name="purpose" value="slim" id="slim" checked>
добавь disabled состояние

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +                  </label>
проверь состояния

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +                <textarea class="form__input form__textarea" name="comment" placeholder="Расскажите обо всех повадках кота"></textarea>
проверь состояния

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +                  <label class="form__label form__label--checkbox" for="vitamins">Витамины</label>
добавь disabled

2020-12-29 22:30 UTC, kosovych commented on source/form.html
>              </a>
проверь состояния (внимание на лого)

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +                <div class="fieldset__wrapper--bordered">
модификатор без элемента

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +              <div class="fieldset__wrapper fieldset__wrapper--last wrapper">
у элемента fieldset__wrapper нет блока fieldset

2020-12-29 22:30 UTC, kosovych commented on source/form.html
> +            <h3 class="page-footer__heading page-footer__heading--form">Приглашаем <br> к сотрудничеству дилеров!</h3>
пропустил h2

2021-01-04 13:21 UTC, RomanTkachev commented on source/form.html
>      <header class="page-header">
исправил

2021-01-04 13:21 UTC, RomanTkachev commented on source/form.html
>      <header class="page-header">
исправил

2021-01-04 13:21 UTC, RomanTkachev commented on source/form.html
>                  </label>
убрал дерганье

2021-01-04 13:25 UTC, RomanTkachev commented on source/form.html
> +                  <input class="form__input form__input--radio" type="radio" name="purpose" value="slim" id="slim" checked>
добавил для radio

2021-01-04 13:28 UTC, RomanTkachev commented on source/form.html
> +                <textarea class="form__input form__textarea" name="comment" placeholder="Расскажите обо всех повадках кота"></textarea>
не вижу в стайлгайде прописанных состояний для textarea, где их посмотреть?

2021-01-04 13:31 UTC, RomanTkachev commented on source/form.html
> +                  <label class="form__label form__label--checkbox" for="vitamins">Витамины</label>
добавил для checkbox

2021-01-04 13:53 UTC, RomanTkachev commented on source/form.html
> +                  </label>
добавил для phone

2021-01-04 14:01 UTC, RomanTkachev commented on source/form.html
>              </a>
поправил

2021-01-04 14:17 UTC, RomanTkachev commented on source/form.html
> +            <h3 class="page-footer__heading page-footer__heading--form">Приглашаем <br> к сотрудничеству дилеров!</h3>
добавил h2

2021-01-04 14:19 UTC, RomanTkachev commented on source/form.html
> +                <div class="fieldset__wrapper--bordered">
исправил

2021-01-04 14:24 UTC, RomanTkachev commented on source/form.html
> +              <div class="fieldset__wrapper fieldset__wrapper--last wrapper">
поправил

2021-01-04 19:23 UTC, kosovych commented on source/form.html
> +                  <input class="form__input form__input--radio" type="radio" name="purpose" value="slim" id="slim" checked>
не исправлено. ты добавил disabled для label, а нужно для input

2021-01-04 19:27 UTC, kosovych commented on source/form.html
> +                <textarea class="form__input form__textarea" name="comment" placeholder="Расскажите обо всех повадках кота"></textarea>
@RomanTkachev они должны быть такие же как и для других инпутов

2021-01-04 19:28 UTC, kosovych commented on source/form.html
> +                  <label class="form__label form__label--checkbox" for="vitamins">Витамины</label>
тоже самое что и для радио

2021-01-04 19:36 UTC, kosovych requested changes
для элементов form__input--text form__input--email и form__input--phone у тебя дублируются, но не полностью стили состояний, хотя все эти стили относятся к form__input, они должны быть одинаковы и записаны один раз

2021-01-04 20:36 UTC, RomanTkachev commented on source/form.html
> +                <textarea class="form__input form__textarea" name="comment" placeholder="Расскажите обо всех повадках кота"></textarea>
Добавил

2021-01-04 20:36 UTC, RomanTkachev commented
> для элементов form__input--text form__input--email и form__input--phone у тебя дублируются, но не полностью стили состояний, хотя все эти стили относятся к form__input, они должны быть одинаковы и записаны один раз

объединил стили состояний в рамках form__input

2021-01-04 20:58 UTC, RomanTkachev commented on source/form.html
> +                  <input class="form__input form__input--radio" type="radio" name="purpose" value="slim" id="slim" checked>
Исправил, добавил для input

2021-01-04 21:25 UTC, RomanTkachev commented on source/form.html
> +                  <label class="form__label form__label--checkbox" for="vitamins">Витамины</label>
Исправил

2021-01-04 22:01 UTC, merged