Стилизация страницы каталога
htmlacademy-adaptive/235287-cat-energy-21 pull request #13
Opened 2021-01-06 14:11 UTC by RomanTkachev

добавил стилизацию страницы каталога + мелки правки страницы формы

2021-01-08 20:32 UTC, kosovych requested changes

2021-01-08 20:32 UTC, kosovych commented on source/catalog.html
>      <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104060473-a0ba3400-51ff-11eb-8242-12f8bcfff215.png)
PP mobile

2021-01-08 20:32 UTC, kosovych commented on source/catalog.html
>      <header class="page-header">
![image](https://user-images.githubusercontent.com/19348382/104061075-90568900-5200-11eb-80a9-222a69248a52.png)

2021-01-09 19:34 UTC, RomanTkachev commented on source/catalog.html
>      <header class="page-header">
Поправил

2021-01-09 19:35 UTC, RomanTkachev commented on source/catalog.html
>      <header class="page-header">
Поправил

2021-01-09 22:31 UTC, merged