Адаптивная графика
htmlacademy-adaptive/235287-cat-energy-21 pull request #14
Opened 2021-01-10 19:36 UTC by RomanTkachev

2021-01-10 22:10 UTC, kosovych requested changes

2021-01-10 22:10 UTC, kosovych commented on source/index.html
>      <header class="page-header page-header-index">
![image](https://user-images.githubusercontent.com/19348382/104136643-24ab2200-53a0-11eb-84c3-34fd5a03d1c0.png)
кота расплющило

2021-01-10 22:10 UTC, kosovych commented on source/index.html
>      <header class="page-header page-header-index">
![image](https://user-images.githubusercontent.com/19348382/104136718-8e2b3080-53a0-11eb-82b0-e21ddc1cc880.png)
подтяни ПП на картинках

2021-01-10 22:10 UTC, kosovych commented on source/index.html
>        <div class="page-header__wrapper wrapper">
![image](https://user-images.githubusercontent.com/19348382/104136747-bd41a200-53a0-11eb-8edf-d4a7ae6e4f09.png)
по всему списку продуктов

2021-01-10 22:10 UTC, kosovych commented on source/index.html
>          <a class="page-header__logo-image" href="">
![image](https://user-images.githubusercontent.com/19348382/104136777-ed894080-53a0-11eb-8f15-827fc054a569.png)

2021-01-11 08:08 UTC, RomanTkachev commented on source/index.html
>        <div class="page-header__wrapper wrapper">
Поправил

2021-01-11 08:20 UTC, RomanTkachev commented on source/index.html
>          <a class="page-header__logo-image" href="">
поправил

2021-01-11 08:35 UTC, RomanTkachev commented on source/index.html
>      <header class="page-header page-header-index">
поправил

2021-01-11 08:48 UTC, RomanTkachev commented on source/index.html
>      <header class="page-header page-header-index">
поправил

2021-01-11 19:02 UTC, merged